{
    "sugarcube-2": {
        "macros": {
            "getInventoryTab": {},
            "getStarterEquipment": {},
            "getCurrentlyEquipped": {},
            "equipItem": {},
            "unequipItemHelper": {},
            "useItem": {},
            "playerAvatar": {},
        }
    }
}