{
    "sugarcube-2": {
        "macros": {
            "relationships": {},
            "joinAdventurersGuild": {},
            "getOrdTechEntranceExam": {},
            "getEntranceExamScore": {}
        }
    }
}